# Generated by Django 4.2.27 on 2025-12-22 16:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Front Bumper, Engine Oil Filter', max_length=200)),
                ('part_number', models.CharField(blank=True, help_text='OEM part number if available', max_length=100)),
                ('category', models.CharField(help_text='e.g., Engine, Body, Electrical', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(default='Used - Good', help_text='Condition of the part', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('slug', models.SlugField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Honda City, Royal Enfield Classic 350', max_length=200)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year_from', models.PositiveIntegerField(help_text='Manufacturing year start')),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Leave blank if still in production', null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Model',
                'verbose_name_plural': 'Vehicle Models',
                'ordering': ['vehicle_type', 'manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassis_number', models.CharField(help_text='VIN or Chassis Number', max_length=100, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('odometer_reading', models.PositiveIntegerField(blank=True, help_text='Mileage in KM', null=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('acquired_date', models.DateField()),
                ('acquired_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Parts extracted and added to stock')),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_stocks', to='myapp.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Vehicle Stock',
                'verbose_name_plural': 'Vehicle Stocks',
                'ordering': ['-acquired_date'],
            },
        ),
        migrations.CreateModel(
            name='PartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.PositiveIntegerField(default=2, help_text='Alert when stock falls below this')),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about stock')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='myapp.part')),
            ],
            options={
                'verbose_name': 'Part Stock',
                'verbose_name_plural': 'Part Stocks',
            },
        ),
        migrations.AddField(
            model_name='part',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='myapp.vehiclemodel'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['vehicle_model', 'category'], name='myapp_part_vehicle_099e0f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('vehicle_model', 'slug')},
        ),
    ]
