# Generated by Django 5.2.9 on 2025-12-30 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partstock',
            name='id',
        ),
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(default='Used - Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='partstock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='partstock',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='partstock',
            name='part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stock', serialize=False, to='myapp.part'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year_from',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='chassis_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='odometer_reading',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['slug'], name='myapp_part_slug_cd1c0b_idx'),
        ),
    ]
